import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"
import { TailwindIndicator } from "@/components/tailwind-indicator"
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner"
import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      className={`${GeistSans.variable} ${GeistMono.variable}`}
      lang="en"
      suppressHydrationWarning // temporarily: https://github.com/pacocoursey/next-themes/tree/bf0c5a45eaf6fb2b336a6b93840e4ec572bc08c8?tab=readme-ov-file#with-app
    >
      <body className={"h-screen w-full"}>
        {/* <Navbar /> */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
          enableSystem
        >
          {children}
        </ThemeProvider>
        <Toaster />
        <TailwindIndicator />
      </body>
    </html>
  )
}
