BEGIN;

CREATE TABLE IF NOT EXISTS public.users (
    id uuid NOT NULL PRIMARY KEY, -- UUID from auth.users
    created_at timestamp with time zone DEFAULT now(),
    email text,
    first_name text,
    last_name text
);
-- FUNCTION
CREATE OR REPLACE FUNCTION public.handle_new_user ()
    RETURNS TRIGGER
    AS $$
BEGIN
    INSERT INTO public.users (id, email)
        VALUES (NEW.id, NEW.email);
    RETURN new;
END;
$$
LANGUAGE plpgsql
SECURITY DEFINER;
CREATE OR REPLACE FUNCTION public.handle_delete_user ()
    RETURNS TRIGGER
    AS $$
BEGIN
    DELETE FROM public.users
    WHERE id = OLD.id;
    RETURN old;
END;
$$
LANGUAGE plpgsql
SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE PROCEDURE public.handle_new_user ();
DROP TRIGGER IF EXISTS on_auth_user_deleted ON auth.users;

CREATE TRIGGER on_auth_user_deleted
    AFTER DELETE ON auth.users
    FOR EACH ROW
    EXECUTE PROCEDURE public.handle_delete_user ();
COMMIT;

create table "public"."workout_rows" (
    "id" bigint generated by default as identity not null,
    "workout_id" uuid,
    "row_data" jsonb
);

create table "public"."workouts" (
    "id" uuid not null,
    "created_at" timestamp with time zone default now(),
    "version" text not null,
    "user_id" uuid not null
);


CREATE UNIQUE INDEX workout_rows_pkey ON public.workout_rows USING btree (id);
CREATE UNIQUE INDEX workout_plans_pkey ON public.workouts USING btree (id);

COMMIT;

